default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: fafer_development
  user:
  password:

test:
  <<: *default
  database: fafer_test
  user:
  password:

production:
  <<: *default
  database: fafer_production
  user:
  password:
