#!/bin/bash

export CI_BUILD_ID="$HEROKU_TEST_RUN_ID"
export CI_NAME="heroku"
export GIT_BRANCH="$HEROKU_TEST_RUN_BRANCH"
export GIT_COMMIT_SHA="$HEROKU_TEST_RUN_COMMIT_VERSION"
export GIT_COMMITTED_AT="$(date +%s)"

ruby_filename="coverage/codeclimate.rb.json"

# run the ruby test suite
bundle exec rake spec

# format ruby coverage
./cc-test-reporter format-coverage --output $ruby_filename

# sum code coverage and send to codeclimate
./cc-test-reporter sum-coverage $ruby_filename
./cc-test-reporter upload-coverage
